CREATE TABLE sys_user(
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(32) NOT NULL,
	user_name VARCHAR(32) NOT NULL,
	password VARCHAR(128) NOT NULL,
	is_delete TINYINT UNSIGNED NOT NULL,
	password_update_time DATETIME NOT NULL,
	last_login_time DATETIME NOT NULL,
	create_time DATETIME NOT NULL,
	update_time DATETIME NOT NULL,
	PRIMARY KEY (id)	
);
CREATE TABLE sys_role(
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(32) NOT NULL,
	display_name VARCHAR(64) NOT NULL,
	is_default TINYINT UNSIGNED NOT NULL,
	is_deleted TINYINT UNSIGNED NOT NULL,
	create_time DATETIME NOT NULL,
	update_time DATETIME NOT NULL,
	PRIMARY KEY (id)
);
CREATE TABLE sys_user_role(
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	role_id BIGINT UNSIGNED NOT NULL,
	user_id BIGINT UNSIGNED NOT NULL,
	create_time DATETIME NOT NULL,
	PRIMARY KEY (id)
);
CREATE TABLE sys_permission(
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(128) NOT NULL,
	display_name VARCHAR(128) NOT NULL,
	is_granted TINYINT UNSIGNED NOT NULL,
	create_time DATETIME NOT NULL,
	update_time DATETIME NOT NULL,
	PRIMARY KEY (id)
);
CREATE TABLE sys_permission_role(
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	role_id BIGINT UNSIGNED NOT NULL,
	permission_id BIGINT UNSIGNED NOT NULL,
	create_time DATETIME NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE obj_meetingroom(
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(128) NOT NULL,
	status TINYINT UNSIGNED NOT NULL,
	create_time DATETIME NOT NULL,
	PRIMARY KEY (id)
);

INSERT INTO TABLE obj_meetingroom VALUES("Beijing",1,now())
INSERT INTO TABLE obj_meetingroom VALUES("Shanghai",1,now())